jobs:
  include:
    - install: pip install -r dev-requirements.txt
      python: 3.7
      script:
        - python setup.py lint
      stage: lint
language: python
python:
  - 3.5
  - 3.6
  - 3.7
script:
  - echo "skipping tests"
stages:
  - lint
  - test
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL